# Nom du workflow

name: Django Pipeline

# Définir les actions pour lesquels on appelle le workflow
on:
  push:
    branches:
      - master
      - tests
  pull_request:
    branches:
      - master
      - tests

# Travail du pipeline (ensemble d'étapes que nous allons exécuter)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Installation des dépendences
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Tests
      run:
        coverage run manage.py test

    - name: Coverage Report
      run:
        coverage report

    - name:  Quality Gate
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

